version: '2'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
      - "9501:9501"
      - "2015:2015"
    volumes:
      - /Users/cmha/workstation/g7/myDockerfile/conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - /Users/cmha/workstation/g7/myDockerfile/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /Users/cmha/workstation/g7/myDockerfile/log/nginx/:/var/log/nginx/:rw
    links:
      - php:fpm
    container_name: nginx
    networks:
      default:
        ipv4_address: 172.18.0.3

  php:
    image: yearzero/php56:latest
    expose:
      - "9000"
      - "9501"  # swoole
      - "2015"  # dsl
    volumes:
      - /Users/cmha/workstation/g7/:/var/www/html/:rw
      - /Users/cmha/workstation/g7/myDockerfile/conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - /Users/cmha/workstation/g7/myDockerfile/conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - /Users/cmha/workstation/g7/myDockerfile/log/php-fpm/:/var/log/php-fpm/:rw
    container_name: php56
    networks:
      default:
        ipv4_address: 172.18.0.2
    extra_hosts:
      - "lc.truck_manager_x.com:172.18.0.3"
#      - "ldapservice.chinawayltd.com:172.18.0.3"

#    links:
#      - gearmand:gearmand
#
#  gearmand:
#    image: artefactual/gearmand:latest
#    ports:
#      - "4730:4730"
#    tty: true

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16